routes:
  /about/: about
  /payment/: payment
  /noticias/:
    controller: channel
    template: noticias

collections:
  /:
    permalink: /{slug}/
    template: index

  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

