routes:
  /about/: about
  /payment/: payment

collections:
  /:
    permalink: /{slug}/
    template: index

  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

